linters:
  enable:
    - gosimple
    - staticcheck
    - unused
    - gofmt
    - govet
    - revive # replacement for golint

linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
